import type { Deck, Card as CardType } from './types';

export const clashRoyaleCards: CardType[] = [
    { name: 'Knight', iconUrl: 'https://placehold.co/150x180.png?text=Knight', elixir: 3, releaseOrder: 1 },
    { name: 'Archers', iconUrl: 'https://placehold.co/150x180.png?text=Archers', elixir: 3, releaseOrder: 1 },
    { name: 'Goblins', iconUrl: 'https://placehold.co/150x180.png?text=Goblins', elixir: 2, releaseOrder: 1 },
    { name: 'Giant', iconUrl: 'https://placehold.co/150x180.png?text=Giant', elixir: 5, releaseOrder: 1 },
    { name: 'P.E.K.K.A', iconUrl: 'https://placehold.co/150x180.png?text=P.E.K.K.A', elixir: 7, releaseOrder: 1 },
    { name: 'Minions', iconUrl: 'https://placehold.co/150x180.png?text=Minions', elixir: 3, releaseOrder: 1 },
    { name: 'Balloon', iconUrl: 'https://placehold.co/150x180.png?text=Balloon', elixir: 5, releaseOrder: 1 },
    { name: 'Witch', iconUrl: 'https://placehold.co/150x180.png?text=Witch', elixir: 5, releaseOrder: 1 },
    { name: 'Arrows', iconUrl: 'https://placehold.co/150x180.png?text=Arrows', elixir: 3, releaseOrder: 1 },
    { name: 'Fireball', iconUrl: 'https://placehold.co/150x180.png?text=Fireball', elixir: 4, releaseOrder: 1 },
    { name: 'Rocket', iconUrl: 'https://placehold.co/150x180.png?text=Rocket', elixir: 6, releaseOrder: 1 },
    { name: 'Goblin Barrel', iconUrl: 'https://placehold.co/150x180.png?text=Goblin_Barrel', elixir: 3, releaseOrder: 1 },
    { name: 'Hog Rider', iconUrl: 'https://placehold.co/150x180.png?text=Hog_Rider', elixir: 4, releaseOrder: 1 },
    { name: 'Valkyrie', iconUrl: 'https://placehold.co/150x180.png?text=Valkyrie', elixir: 4, releaseOrder: 1 },
    { name: 'Ice Spirit', iconUrl: 'https://placehold.co/150x180.png?text=Ice_Spirit', elixir: 1, releaseOrder: 2 },
    { name: 'Zap', iconUrl: 'https://placehold.co/150x180.png?text=Zap', elixir: 2, releaseOrder: 1 },
    { name: 'Poison', iconUrl: 'https://placehold.co/150x180.png?text=Poison', elixir: 4, releaseOrder: 1 },
    { name: 'Tombstone', iconUrl: 'https://placehold.co/150x180.png?text=Tombstone', elixir: 3, releaseOrder: 1 },
    { name: 'Mega Minion', iconUrl: 'https://placehold.co/150x180.png?text=Mega_Minion', elixir: 3, releaseOrder: 3 },
    { name: 'Guards', iconUrl: 'https://placehold.co/150x180.png?text=Guards', elixir: 3, releaseOrder: 2 },
    { name: 'The Log', iconUrl: 'https://placehold.co/150x180.png?text=The_Log', elixir: 2, releaseOrder: 3 },
    { name: 'Princess', iconUrl: 'https://placehold.co/150x180.png?text=Princess', elixir: 3, releaseOrder: 2 },
    { name: 'Ice Wizard', iconUrl: 'https://placehold.co/150x180.png?text=Ice_Wizard', elixir: 3, releaseOrder: 2 },
    { name: 'Miner', iconUrl: 'https://placehold.co/150x180.png?text=Miner', elixir: 3, releaseOrder: 2 },
    { name: 'Lava Hound', iconUrl: 'https://placehold.co/150x180.png?text=Lava_Hound', elixir: 7, releaseOrder: 2 },
    { name: 'Mega Knight', iconUrl: 'https://placehold.co/150x180.png?text=Mega_Knight', elixir: 7, releaseOrder: 5 },
    { name: 'Electro Wizard', iconUrl: 'https://placehold.co/150x180.png?text=Electro_Wizard', elixir: 4, releaseOrder: 4 },
    { name: 'Bandit', iconUrl: 'https://placehold.co/150x180.png?text=Bandit', elixir: 3, releaseOrder: 4 },
    { name: 'Royal Ghost', iconUrl: 'https://placehold.co/150x180.png?text=Royal_Ghost', elixir: 3, releaseOrder: 5 },
    { name: 'Magic Archer', iconUrl: 'https://placehold.co/150x180.png?text=Magic_Archer', elixir: 4, releaseOrder: 5 },
    { name: 'Inferno Tower', iconUrl: 'https://placehold.co/150x180.png?text=Inferno_Tower', elixir: 5, releaseOrder: 1 },
    { name: 'Goblin Gang', iconUrl: 'https://placehold.co/150x180.png?text=Goblin_Gang', elixir: 3, releaseOrder: 4 },
    { name: 'Battle Ram', iconUrl: 'https://placehold.co/150x180.png?text=Battle_Ram', elixir: 4, releaseOrder: 4 },
];

export const topDecks: Deck[] = [
  {
    name: 'Classic Log Bait',
    cards: [
      clashRoyaleCards.find(c => c.name === 'Knight')!,
      clashRoyaleCards.find(c => c.name === 'Princess')!,
      clashRoyaleCards.find(c => c.name === 'Goblin Barrel')!,
      clashRoyaleCards.find(c => c.name === 'The Log')!,
      clashRoyaleCards.find(c => c.name === 'Ice Spirit')!,
      clashRoyaleCards.find(c => c.name === 'Inferno Tower')!,
      clashRoyaleCards.find(c => c.name === 'Rocket')!,
      clashRoyaleCards.find(c => c.name === 'Goblin Gang')!,
    ],
  },
  {
    name: 'LavaLoon',
    cards: [
      clashRoyaleCards.find(c => c.name === 'Lava Hound')!,
      clashRoyaleCards.find(c => c.name === 'Balloon')!,
      clashRoyaleCards.find(c => c.name === 'Tombstone')!,
      clashRoyaleCards.find(c => c.name === 'Mega Minion')!,
      clashRoyaleCards.find(c => c.name === 'Fireball')!,
      clashRoyaleCards.find(c => c.name === 'Zap')!,
      clashRoyaleCards.find(c => c.name === 'Guards')!,
      clashRoyaleCards.find(c => c.name === 'Miner')!,
    ],
  },
  {
    name: 'Pekka Bridge Spam',
    cards: [
      clashRoyaleCards.find(c => c.name === 'P.E.K.K.A')!,
      clashRoyaleCards.find(c => c.name === 'Battle Ram')!,
      clashRoyaleCards.find(c => c.name === 'Bandit')!,
      clashRoyaleCards.find(c => c.name === 'Royal Ghost')!,
      clashRoyaleCards.find(c => c.name === 'Magic Archer')!,
      clashRoyaleCards.find(c => c.name === 'Zap')!,
      clashRoyaleCards.find(c => c.name === 'Poison')!,
      clashRoyaleCards.find(c => c.name === 'Electro Wizard')!,
    ],
  },
];
